parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2017
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
env:
  node: true
  es6: true
  mocha: true
rules:
  require-jsdoc: 0
  typescript/explicit-member-accessibility: 0
